# A rule that includes a single .cpp file and its corresponding header and
# also supplies an additional flag for compilation.
cxx_binary(
  name = 'c',
  srcs = [
    'main.c',
  ],
  deps = [
    '//a:a',
    '//b:b',
    '//libby:libby',
  ],
)
