# A rule that includes a single .cpp file and its corresponding header and
# also supplies an additional flag for compilation.
cxx_library(
  name = 'b',
  srcs = [
    'b.c',
  ],
  headers = [
    'b.h',
  ],
  compiler_flags = [
    '-fno-omit-frame-pointer',
  ],
  deps = [
    '//a:a',
  ],
visibility = [
    'PUBLIC',
  ],
)
